name: Cloud-Network-Sync

on:
  workflow_dispatch:

jobs:
  run-sync:
    runs-on: ubuntu-latest
    # ODSTRANĚNA MATICE 20 - Teď to poběží jako jeden brutální stroj, který GitHub nezablokuje
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install aiohttp
      - name: Run Optimizer Engine
        run: python optimizer.py
        
